package org.persist.dao;

// Generated 2013-3-1 15:41:13 by Hibernate Tools 3.4.0.CR1

/**
 * MhpromotionPicId generated by hbm2java
 */
public class MhpromotionPicId implements java.io.Serializable {

	private String id;
	private String pic;

	public MhpromotionPicId() {
	}

	public MhpromotionPicId(String id, String pic) {
		this.id = id;
		this.pic = pic;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MhpromotionPicId))
			return false;
		MhpromotionPicId castOther = (MhpromotionPicId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getPic() == castOther.getPic()) || (this.getPic() != null
						&& castOther.getPic() != null && this.getPic().equals(
						castOther.getPic())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getPic() == null ? 0 : this.getPic().hashCode());
		return result;
	}

}
