package org.persist.dao;

// Generated 2013-3-1 15:41:13 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.ListUtils;

/**
 * Mhpromotion generated by hbm2java
 */
public class Mhpromotion implements java.io.Serializable {

	private String id;
	private String title;
	private String title2;
	private String summary;
	private String detail;
	private String address;
	private String phone;
	private MhpromotionOnline mhpromotionOnline;
	private List<MhpromotionPic> mhpromotionPics = new ArrayList<MhpromotionPic>(0);
	private MhpromotionCategoryRef mhpromotionCategoryRef;

	public Mhpromotion() {
	}

	public Mhpromotion(String id) {
		this.id = id;
	}

	public Mhpromotion(String id, String title, String title2, String summary,
			String detail, String address, String phone,
			MhpromotionOnline mhpromotionOnline,
			List<MhpromotionPic> mhpromotionPics,
			MhpromotionCategoryRef mhpromotionCategoryRef) {
		this.id = id;
		this.title = title;
		this.title2 = title2;
		this.summary = summary;
		this.detail = detail;
		this.address = address;
		this.phone = phone;
		this.mhpromotionOnline = mhpromotionOnline;
		this.mhpromotionPics = mhpromotionPics;
		this.mhpromotionCategoryRef = mhpromotionCategoryRef;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle2() {
		return this.title2;
	}

	public void setTitle2(String title2) {
		this.title2 = title2;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public MhpromotionOnline getMhpromotionOnline() {
		return this.mhpromotionOnline;
	}

	public void setMhpromotionOnline(MhpromotionOnline mhpromotionOnline) {
		this.mhpromotionOnline = mhpromotionOnline;
	}

	public List<MhpromotionPic> getMhpromotionPics() {
		return this.mhpromotionPics;
	}

	public void setMhpromotionPics(List<MhpromotionPic> mhpromotionPics) {
		Collections.reverse(mhpromotionPics);
		this.mhpromotionPics = mhpromotionPics;
	}

	public MhpromotionCategoryRef getMhpromotionCategoryRef() {
		return this.mhpromotionCategoryRef;
	}

	public void setMhpromotionCategoryRef(
			MhpromotionCategoryRef mhpromotionCategoryRef) {
		this.mhpromotionCategoryRef = mhpromotionCategoryRef;
	}
	
//	public static void main(String[] args) {
//		Mhpromotion m = new Mhpromotion();
//		List<MhpromotionPic> ps = new ArrayList<MhpromotionPic>();
//		MhpromotionPic e = new MhpromotionPic();
//		e.setPorder(1);
//		ps.add(e);
//		MhpromotionPic e1 = new MhpromotionPic();
//		e1.setPorder(2);
//		ps.add(e1);
//		m.setMhpromotionPics(ps);
//		
//		
//		for(MhpromotionPic p:m.getMhpromotionPics()){
//			System.out.println(p.getPorder());
//		}
//		
//		
//	}

}
