package org.persist.dao;

// Generated 2013-3-1 15:41:13 by Hibernate Tools 3.4.0.CR1

/**
 * MhpromotionOnline generated by hbm2java
 */
public class MhpromotionOnline implements java.io.Serializable {

	private String pid;
	private Mhpromotion mhpromotion;
	private Integer porder;
	private Integer hot;

	public MhpromotionOnline() {
	}

	public MhpromotionOnline(Mhpromotion mhpromotion) {
		this.mhpromotion = mhpromotion;
	}

	public MhpromotionOnline(Mhpromotion mhpromotion, Integer porder,
			Integer hot) {
		this.mhpromotion = mhpromotion;
		this.porder = porder;
		this.hot = hot;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public Mhpromotion getMhpromotion() {
		return this.mhpromotion;
	}

	public void setMhpromotion(Mhpromotion mhpromotion) {
		this.mhpromotion = mhpromotion;
	}

	public Integer getPorder() {
		return this.porder;
	}

	public void setPorder(Integer porder) {
		this.porder = porder;
	}

	public Integer getHot() {
		return this.hot;
	}

	public void setHot(Integer hot) {
		this.hot = hot;
	}

}
